source "https://supermarket.getchef.com"

cookbook 'selinux'
cookbook 'sudo'
cookbook 'git'
cookbook 'ruby_build'
cookbook 'ruby-env', path: './site-cookbooks/ruby-env'
cookbook 'nodejs'
cookbook 'nginx'
cookbook 'redis'
cookbook 'td-agent'
